# Cross-sweep trend table: every archived sweep, every class, one row each.
# A sibling of analyze-sweep.ps1, which reads one sweep; see #61.
# Generated, never maintained -- the archive directories are the ledger (#175).
param(
    [string]   $Glob = 'build/results/sweep-*',
    [string[]] $Dirs,
    [string]   $Out,
    [string]   $Class,
    [switch]   $NoMatrix
)
$ErrorActionPreference = 'Stop'

$lines = New-Object System.Collections.Generic.List[string]
function Say([string]$s = '') { $lines.Add($s) }

function Read-Json([string]$Path) {
    try { return (Get-Content -LiteralPath $Path -Raw -Encoding UTF8 | ConvertFrom-Json) }
    catch { return $null }
}
function Distinct($vals) { @($vals | Where-Object { "$_" } | Select-Object -Unique | Sort-Object) }
function Show($v, $none = '?') {
    # @($null).Count is 1 in PS 5.1, so an empty pipeline would read as one value.
    $a = @($v | Where-Object { "$_" -ne '' })
    if ($a.Count -eq 0) { return $none }
    if ($a.Count -eq 1) { return "$($a[0])" }
    return '**' + ($a -join ' / ') + '**'
}

# ------------------------------------------------------------------ gather --
if ($Dirs) { $dirList = @($Dirs | ForEach-Object { Get-Item -LiteralPath $_ }) }
else       { $dirList = @(Get-Item -Path $Glob -ErrorAction SilentlyContinue | Where-Object { $_.PSIsContainer }) }
$dirList = @($dirList | Sort-Object Name)
if ($dirList.Count -eq 0) { throw "no sweep directories matched '$Glob'" }

$sweeps = @()
$empty  = @()
foreach ($d in $dirList) {
    $rows = @()
    foreach ($f in @(Get-ChildItem -LiteralPath $d.FullName -Filter '*.json' -File)) {
        if ($f.Name -match '\.soak\.json$' -or $f.Name -match '\.dossier\.json$') { continue }
        $r = Read-Json $f.FullName
        if (-not $r -or -not $r.Class) { continue }
        $rows += [pscustomobject]@{ Row = $r; Soak = Read-Json (Join-Path $d.FullName ($f.BaseName + '.soak.json')) }
    }
    if ($rows.Count -eq 0) { $empty += $d.Name; continue }

    # The fingerprint comes from the per-run facts, not stamps.txt: the run
    # recorded what it ran under, and sweeps 01-16 have no stamp file (#214).
    $soaks = @($rows | ForEach-Object { $_.Soak } | Where-Object { $_ })

    # Start zone is a per-CLASS fact, not a policy one -- the DLC class families
    # start behind a town intro, so one sweep legitimately holds several (#123).
    # The policy is the zone the sweep put most of its classes in.
    $zoneTally = @($rows | ForEach-Object { "$($_.Row.StartZone)" } | Where-Object { $_ } |
                  Group-Object | Sort-Object Count -Descending)
    $zoneMain  = if ($zoneTally.Count) { $zoneTally[0].Name } else { '' }
    $zoneOther = ($zoneTally | Select-Object -Skip 1 | Measure-Object -Property Count -Sum).Sum

    $sweeps += [pscustomobject]@{
        Name    = $d.Name
        Rows    = $rows
        NoSoak  = @($rows | Where-Object { -not $_.Soak }).Count
        When    = $(
            $st = @($soaks | ForEach-Object { $_.started } | Where-Object { $_ } | Sort-Object)
            if ($st.Count) { ($st[0] -replace 'T', ' ') -replace '\..*$', '' } else { '' })
        Trees     = Distinct @($soaks | ForEach-Object { $_.build.trees })
        Protos    = Distinct @($soaks | ForEach-Object { $_.build.proto })
        Hosts     = Distinct @($soaks | ForEach-Object { $_.build.host })
        Commits   = Distinct @($soaks | ForEach-Object { $_.build.short })
        Rules     = Distinct @($soaks | ForEach-Object { $_.rules_source })
        Mins      = Distinct @($soaks | ForEach-Object { $_.limits.max_minutes })
        Conds     = Distinct @($soaks | ForEach-Object { (@($_.conditions) -join ' ') })
        CondSet   = (Distinct @($soaks | ForEach-Object { @($_.conditions) })) -join ' '
        Zone      = $zoneMain
        ZoneOther = [int]$zoneOther
    }
}
$sweeps = @($sweeps | Sort-Object @{ E = { if ($_.When) { $_.When } else { '9999' } } }, Name)

if ($Class) {
    foreach ($s in $sweeps) { $s.Rows = @($s.Rows | Where-Object { $_.Row.Class -eq $Class }) }
    $sweeps = @($sweeps | Where-Object { $_.Rows.Count -gt 0 })
    if ($sweeps.Count -eq 0) { throw "no rows for class '$Class'" }
    foreach ($s in $sweeps) { $s.NoSoak = @($s.Rows | Where-Object { -not $_.Soak }).Count }
}

$totalRows = ($sweeps | ForEach-Object { $_.Rows.Count } | Measure-Object -Sum).Sum
Say '# Sweep trend'
Say ''
Say "$($sweeps.Count) sweep(s), $totalRows run(s)$(if ($Class) { ", class $Class" }). Generated by ``tools/analyze-trend.ps1``; the archive directories are the ledger (#61)."
if ($empty.Count -gt 0) { Say ''; Say "$($empty.Count) matched directory(ies) held no result rows and are absent below: $($empty -join ', ')." }
Say ''

# ------------------------------------------------------------- fingerprint --
# Protocol and policy only. Host and commit are provenance and get their own
# line: a sweep spanning two of either is a MERGED sweep, not a broken one.
function Fp($s) { "$($s.Trees -join ',')|$($s.Protos -join ',')|$($s.Zone)|$($s.CondSet)|$($s.Mins -join ',')|$($s.Rules -join ',')" }

Say '## Sweeps'
Say ''
Say '| # | sweep | when | runs | host | commit | trees | proto | start zone | minutes | rules |'
Say '|---:|---|---|---:|---|---|---|---|---|---:|---|'
$n = 0
foreach ($s in $sweeps) {
    $n++
    $s | Add-Member -NotePropertyName Ord -NotePropertyValue $n -Force
    $runs = "$($s.Rows.Count)$(if ($s.NoSoak) { " (+$($s.NoSoak) no soak)" })"
    $zone = "$($s.Zone)$(if ($s.ZoneOther) { " (+$($s.ZoneOther) class-specific)" })"
    Say "| $($s.Ord) | $($s.Name) | $($s.When) | $runs | $(Show $s.Hosts) | $(Show $s.Commits) | $(Show $s.Trees) | $(Show $s.Protos '--') | $zone | $(Show $s.Mins) | $(Show $s.Rules) |"
}
Say ''

$split = @($sweeps | Where-Object { $_.Trees.Count -gt 1 -or $_.Protos.Count -gt 1 -or $_.Conds.Count -gt 1 -or $_.Mins.Count -gt 1 -or $_.Rules.Count -gt 1 })
if ($split.Count -gt 0) {
    Say "**$($split.Count) sweep(s) are not internally one measurement**: their own runs disagree on the protocol or the stop policy, so that sweep's headline is a blend rather than a measurement (#219): $(($split | ForEach-Object { $_.Name }) -join ', ')."
    Say ''
}
$merged = @($sweeps | Where-Object { $_.Hosts.Count -gt 1 -or $_.Commits.Count -gt 1 })
if ($merged.Count -gt 0) {
    Say "$($merged.Count) sweep(s) were assembled from more than one host or commit -- expected of a merged remote sweep, and the reason the halves must agree on trees and proto before merging (#182, #214): $(($merged | ForEach-Object { $_.Name }) -join ', ')."
    Say ''
}
$noProto = @($sweeps | Where-Object { $_.Protos.Count -eq 0 })
if ($noProto.Count -gt 0) {
    Say "``proto`` is absent from $($noProto.Count) sweep(s), recorded before the field existed (#214). For those, identical ``trees`` does **not** mean identical protocol -- ``soak.ps1`` could differ with nothing on disk to show it."
    Say ''
}

# -------------------------------------------------------------- boundaries --
Say '## Comparability boundaries'
Say ''
$bounds = @()
for ($i = 1; $i -lt $sweeps.Count; $i++) {
    $a = $sweeps[$i - 1]; $b = $sweeps[$i]
    if ((Fp $a) -eq (Fp $b)) { continue }
    $what = @()
    if (($a.Trees  -join ',') -ne ($b.Trees  -join ',')) { $what += "trees $(Show $a.Trees) -> $(Show $b.Trees)" }
    if (($a.Protos -join ',') -ne ($b.Protos -join ',')) { $what += "proto $(Show $a.Protos '--') -> $(Show $b.Protos '--')" }
    if ($a.Zone -ne $b.Zone)                             { $what += "start zone $($a.Zone) -> $($b.Zone)" }
    if (($a.Mins   -join ',') -ne ($b.Mins   -join ',')) { $what += "minutes $(Show $a.Mins) -> $(Show $b.Mins)" }
    if (($a.Rules  -join ',') -ne ($b.Rules  -join ',')) { $what += "rules $(Show $a.Rules) -> $(Show $b.Rules)" }
    if ($a.CondSet -ne $b.CondSet) {
        $ac = @($a.CondSet -split ' ' | Where-Object { $_ }); $bc = @($b.CondSet -split ' ' | Where-Object { $_ })
        $gone = @($ac | Where-Object { $bc -notcontains $_ }); $new = @($bc | Where-Object { $ac -notcontains $_ })
        $what += "conditions$(if ($new) { " +$($new -join ' ')" })$(if ($gone) { " -$($gone -join ' ')" })"
    }
    if ($what.Count -eq 0) { continue }
    $bounds += [pscustomobject]@{ At = $b.Name; Prev = $a.Name; What = $what }
}
if ($bounds.Count -eq 0) {
    Say 'None: every sweep here shares one fingerprint, so the tables below are one measurement.'
} else {
    Say "$($bounds.Count) point(s) where the protocol or the policy changed. **A trend read across one of these is not one measurement** -- it is #187's flattering denominator in a new coat, and the boundary belongs beside any claim that spans it."
    Say ''
    foreach ($b in $bounds) { Say "- **$($b.Prev) -> $($b.At)**: $($b.What -join '; ')" }
}
Say ''

# ------------------------------------------------------------------ matrix --
$allOutcomes = @($sweeps | ForEach-Object { $_.Rows } | ForEach-Object { "$($_.Row.Outcome)" } | Where-Object { $_ } | Select-Object -Unique | Sort-Object)
$code = @{}; $used = @{}
foreach ($o in $allOutcomes) {
    $c = $o.Substring(0, 1).ToUpper(); $k = 1
    while ($used.ContainsKey($c) -and $k -lt $o.Length) { $c = $o.Substring($k, 1).ToUpper(); $k++ }
    $used[$c] = $true; $code[$o] = $c
}
$classes = @($sweeps | ForEach-Object { $_.Rows } | ForEach-Object { "$($_.Row.Class)" } | Where-Object { $_ } | Select-Object -Unique | Sort-Object)

if (-not $NoMatrix) {
    Say '## Outcome matrix'
    Say ''
    Say "Legend: $((($allOutcomes | ForEach-Object { "``$($code[$_])`` $_" }) -join ', ')); ``.`` not run. Columns are the ``#`` column of the Sweeps table above. **The matrix does not draw the boundaries** -- read it against the section above before comparing two columns."
    Say ''
    Say '```'
    $w = ($classes | Measure-Object -Property Length -Maximum).Maximum
    Say ("{0} {1}" -f ''.PadRight($w), ((@($sweeps | ForEach-Object { "$($_.Ord)".PadLeft(2) })) -join ''))
    foreach ($c in $classes) {
        $cells = foreach ($s in $sweeps) {
            $r = @($s.Rows | Where-Object { $_.Row.Class -eq $c })
            if ($r.Count -eq 0) { ' .' } else { " $($code["$($r[0].Row.Outcome)"])" }
        }
        Say ("{0} {1}" -f $c.PadRight($w), ($cells -join ''))
    }
    Say '```'
    Say ''
}

# --------------------------------------------------------------- per class --
Say '## Per class'
Say ''
foreach ($c in $classes) {
    $hist = @()
    foreach ($s in $sweeps) {
        foreach ($r in @($s.Rows | Where-Object { $_.Row.Class -eq $c })) {
            $hist += [pscustomobject]@{ Sweep = $s.Name; R = $r.Row }
        }
    }
    if ($hist.Count -eq 0) { continue }
    $outs = @($hist | Group-Object { $_.R.Outcome } | Sort-Object Count -Descending |
             ForEach-Object { "$($_.Name) x$($_.Count)" })
    Say "### $c"
    Say ''
    Say "$($hist.Count) run(s): $($outs -join ', ')"
    Say ''
    Say '| sweep | outcome | start zone | turns | deaths | top stop |'
    Say '|---|---|---|---:|---:|---|'
    foreach ($h in $hist) {
        $top = "$($h.R.TopStop)" -replace '\|', '/'
        Say "| $($h.Sweep) | $($h.R.Outcome) | $($h.R.StartZone) | $($h.R.Turns) | $($h.R.Deaths) | $top |"
    }
    Say ''
}

$text = $lines -join "`r`n"
if ($Out) { Set-Content -LiteralPath $Out -Value $text -Encoding UTF8; Write-Host "[trend] wrote $Out ($($lines.Count) lines)" }
else { Write-Output $text }
